catalog/urls.py
from django.urls import path
from . import views
from .views import EventListView, AboutPageView, IndexPageView

urlpatterns = [
    path("", IndexPageView.as_view(), name="index"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("events/", views.EventListView.as_view(), name="events"),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event-detail'),
    path("leaders/", views.LeaderListView.as_view(), name="leaders"),
    path('leader/<int:pk>', views.LeaderDetailView.as_view(), name='leader-detail'),
    path('myevents/', views.AttendedEventByUserListView.as_view(), name='my-attending'),
    path('mycohorts/', views.Cohort_and_Attendees_List_View.as_view(), name='my-leading'),

    path('eventinstance/<int:pk>/update/', views.EventInstanceUpdate.as_view(),
         name='event-instance-update'),
    path('eventinstance/<int:pk>/delete/', views.EventInstanceDelete.as_view(),
         name='event-instance-delete'),

    path('event/create/', views.EventCreate.as_view(), name='event-create'),
    path('event/<int:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
]

cohorts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
# Use static() to add URL mapping to serve static
# files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User, AbstractUser
import uuid


class Event(models.Model):
    title = models.CharField(max_length=200)

    date = models.DateTimeField(blank=True)

    attendees = models.IntegerField(default=20)

    leader = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    STATUS = (
        ('t', 'Teaching'),
        ('n', 'Not Teaching'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='t',
    )

    description = models.TextField(max_length=1000,
                                   help_text='Enter a brief description of tevent')

    LEVEL_CHOICES = (
        ('all levels', 'ALL'),
        ('beginner', 'BEGINNER'),
        ('specialized', 'SPECIALIZED'),
    )

    level = models.CharField(max_length=15, choices=LEVEL_CHOICES, default='all')

    LANGUAGE_CHOICES = (
        ('api', 'API'),
        ('css', 'CSS'),
        ('data', 'DATA'),
        ('html', 'HTML'),
        ('javascript', 'JAVASCRIPT'),
    )

    language = models.CharField(max_length=15, choices=LANGUAGE_CHOICES, default='html')

    image = models.ImageField(upload_to='static/img/')

    def get_absolute_url(self):
        return reverse('event-detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class EventInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)

    leader = models.ForeignKey('Leader', on_delete=models.RESTRICT, null=True)

    cohort = models.ForeignKey('Event', on_delete=models.RESTRICT, null=True)

    attendee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    STATUS = (
        ('a', 'Attending'),
        ('w', 'Waitlist'),
        ('n', 'Not Attending'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=True,
        default='a',
    )

    def __str__(self):
        return f'{self.id} ({self.cohort.title})'

    # def get_absolute_url(self):
    #     return reverse('event-detail', args=[str(self.id)])


class Leader(models.Model):
    leader = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               null=True)

    phone = PhoneNumberField(null=False,
                             blank=False,
                             unique=True,
                             help_text='Contact phone number')

    def get_absolute_url(self):
        return reverse('leader-detail', args=[str(self.id)])

    # def __str__(self):
    #     return f'{self.first_name} {self.last_name}'

catalog/views.py
from django.views.generic import TemplateView
from django.views import generic
from catalog.models import Leader
from catalog.models import Event
from catalog.models import EventInstance
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


class IndexPageView(TemplateView):
    template_name = "index.html"


class AboutPageView(TemplateView):
    template_name = "about.html"


class EventListView(generic.ListView):
    template_name = "events.html"
    model = Event
    context_object_name = 'event_list'
    paginate_by = 10
    ordering = ['date']

    # queryset = Event.objects.filter(title__icontains='API')[
    #            :5]  # Get 5 events containing the title API


class EventDetailView(generic.DetailView):
    template_name = "event_detail.html"
    model = Event


class LeaderListView(generic.ListView):
    template_name = "leaders.html"
    model = Leader
    context_object_name = "leader_list"
    paginate_by = 5


class LeaderDetailView(generic.DetailView):
    template_name = "leader_detail.html"
    model = Leader


class AttendedEventByUserListView(LoginRequiredMixin, generic.ListView):
    model = EventInstance
    template_name = 'catalog/eventinstance_list_attended_by_user.html'
    paginate_by = 10

    def get_queryset(self):
        return EventInstance.objects.filter(attendee=self.request.user).filter(
            status__exact='a').order_by('cohort__date')


class Cohort_and_Attendees_List_View(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'catalog/event_list_lead_by_staff.html'
    paginate_by = 10

    def get_queryset(self):
        return Event.objects.filter(leader=self.request.user.id).all().order_by('date')

    def get_context_data(self, **kwargs):
        context = super(Cohort_and_Attendees_List_View, self).get_context_data(**kwargs)
        context['attending_people'] = EventInstance.objects.all()
        return context


class EventInstanceCreate(CreateView):
    model = EventInstance
    fields = ['cohort', 'status', "leader", "attendee"]


class EventInstanceUpdate(UpdateView):
    model = EventInstance
    fields = ['cohort', 'status', "leader", "attendee"]


class EventInstanceDelete(DeleteView):
    model = EventInstance
    success_url = reverse_lazy('eventInstance')


class EventCreate(CreateView):
    model = Event
    fields = ['title', 'date', 'attendees', 'leader', 'status', 'description', 'status',
              'level', 'language', 'image']


class EventUpdate(UpdateView):
    model = Event
    fields = ['title', 'date', 'attendees', 'leader', 'status', 'description', 'status',
              'level', 'language', 'image']


class EventDelete(DeleteView):
    model = Event
    success_url = reverse_lazy('event')

catalog/templates/about.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="page-section about-heading">
            <div class="container">
                <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="/static/img/about.jpg" alt="..." />
                <div class="about-heading-content">
                    <div class="row">
                        <div class="col-xl-9 col-lg-10 mx-auto">
                            <div class="bg-faded rounded p-5">
                                <h2 class="section-heading mb-4">
                                    <span class="section-heading-upper">all skill levels</span>
                                    <span class="section-heading-lower">About Cohorts</span>
                                </h2>
                                <p>Free office hours for programming help - any programming language,
                                    all skill levels. The format is super simple: you come with a
                                    laptop, sit, hang out, and code, and flag down one of the leaders
                                    if you have a question. That's it! If we can't answer your question,
                                    we'll find you someone who can, or at least point you in the right
                                    direction.</p>
                                <p>More experienced folks are also
                                    welcome as mentors.</p>
                                <p class="mb-0">By becoming a member, you agree to abide by and uphold our policies. </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Coding Cohorts</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
    <!-- Add additional CSS in static file -->
  <link rel="icon" type="image/x-icon" href=src="/static/img/favicon.ico">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% block sidebar %}
    <header>
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
            <span class="site-heading-upper text-primary mb-3">programming's never been better</span>
            <span class="site-heading-lower">Coding Cohorts</span>
        </h1>
    </header>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
    <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'index' %}">Coding
        Cohorts</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'index' %}">Home</a></li>
        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'about' %}">About</a></li>
        <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'events' %}">events</a></li>
        {% if user.is_authenticated %}
            <li class="nav-item px-lg-4 text-primary text-uppercase">Logged in
                as:<br>{{ user.get_username }}</li>
            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase"
                                            href="{% url 'my-attending' %}">Attending</a>
            </li>
            {% if user.is_staff %}
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase"
                                                href="{% url 'my-leading' %}">Leading</a>
                </li>
            {% endif %}
            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase"
                                            href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
            </li>
        {% else %}
            <li class="nav-item px-lg-4"><a class="nav-link text-uppercase"
                                            href="{% url 'login' %}?next={{ request.path }}">Login</a>
            </li>
        {% endif %}
    </ul>
{% endblock %}
</div>
</div>
</nav>
{% block content %}{% endblock %}

{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <h3><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a></h3>
                {% endif %}
                <span class="page-current">
                    <h3>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</h3>
                </span>
                {% if page_obj.has_next %}
                    <h3><a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a></h3>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}
{% include 'footer.html' %}
</body>
</html>

catalog/templates/catalog/eventInstance_confirm_delete.html
{% block content %}
    <h1>Delete Your Event </h1>
    <p>Are you sure you want to delete your event: {{ eventInstance }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

catalog/templates/catalog/event_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
<section class="page-section clearfix">
            <div class="container">
                <div class="intro">
                    <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="/static/img/admin-screen.jpg" alt="two people working" />
                    <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                     <h1>Delete Event </h1>
                        <p>Are you sure you want to delete the event: {{ Event }}?</p>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <input type="submit" value="Yes, delete.">
                        </form>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

catalog/templates/catalog/event_form.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded"
                     src="/static/img/admin-screen.jpg"
                     alt="two people working at computer"/>
                <div class="intro-text left-0 text-left bg-faded p-5 rounded">
                    <form action="" method="post">
                        {% csrf_token %}
                        <table>
                            {{ form.as_table }}
                        </table>
                        <input type="submit" value="Submit">
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

catalog/templates/catalog/event_list_lead_by_staff.html
{% extends "base_generic.html" %}

{% block content %}
    <div class="container">
        <!-- Card deck -->
        <div class="card-deck row">
            <!-- Card -->'
            {% if event_list %}
                {% for event in event_list %}
                    <div class="col-xs-12 col-sm-6">
                        <div class="card bg-faded">
                            <!--Card image-->
                            <div class="view overlay">
                                <h2 class=" teaching-card-header section-heading mb-0">
                                    <span class="section-heading-upper"> {{ event.title }}     | {{ event.date }}</span>
                                </h2>
                                <div class="view overlay">
                                    <a href="#!">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card content-->
                                <div class="bg-brown">
                                    <!--Card content-->
                                    {% for person in attending_people %}

                                        {% if  person.cohort.id  ==  event.id %}
                                            <p class="teaching-card-content text-primary">
                                                ( {{ person.status }} )
                                                {{ person.attendee.first_name }} {{ person.attendee.last_name }}
                                            </p>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-center text-primary">You are not leading any cohorts at
                    this time.</p>
            {% endif %}
        </div>
        <!-- Card deck -->
    </div>
{% endblock %}

catalog/templates/catalog/eventinstance_list_attended_by_user.html
{% extends "base_generic.html" %}
{% block content %}
    <div class="container">
        <!-- Card deck -->
        <div class="card-deck row">
            <!-- Card -->
            {% if eventinstance_list %}
                {% for eventinst in eventinstance_list %}
                    <div class="col-xs-12 col-sm-6">
                        <div class="card bg-faded">
                            <!--Card image-->
                            <div class="view overlay">
                                <img class="card-img-top"
                                     src={{ eventinst.cohort.image.url }}  alt="{{ cohort.title }}">
                                <a href="#!">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                            <!--Card content-->
                            <div class="card-body">
                                <!--Title-->
                                <h2 class="section-heading mb-0"><span
                                        class="section-heading-upper">{{ eventinst.cohort.date }}  |  {{ eventinst.cohort.title }}  <a
                                        href="{{ event.get_absolute_url }}">  >></a></span>
                                </h2>
                                <!--Text-->
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <!-- Card -->
            {% else %}
                <p class="text-center text-primary">
                    You are not signed up for any cohorts.</p>
            {% endif %}
        </div>
        <!-- Card deck -->
    </div>
{% endblock %}

catalog/templates/event_detail.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="page-section">
            <div class="container">
                <div class="product-item">
                    <div class="product-item-title d-flex">
                        <div class="bg-faded p-5 d-flex ms-auto rounded">
                            <h2 class="section-heading mb-0">
                                <span class="section-heading-upper">{{ event.date }}</span>
                                <span class="section-heading-lower">{{ event.title }}</span>
                            </h2>
                        </div>
                    </div>
                    <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src={{ event.image.url }} alt={{ event.title }} />
                    <div class="product-item-description d-flex me-auto">
                        <div class="bg-faded p-5 rounded"><p class="mb-0">{{ event.description }}</p>
                        <p>{% if user.is_staff %}
                                        <a href="{% url 'event-update' event.id %}">
                                            Update</a>
                                        - <a href="{% url 'event-delete' event.id %}">
                                            Delete</a>
                                    {% endif %}
                        </p>
                            <h2 class="section-heading mb-0"><span class="section-heading-upper"><br>{{ event.language }} | {{ event.level}}</span></h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>













{% endblock %}

catalog/templates/events.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            <span class="section-heading-lower">Upcoming Events</span>
                        </h2>
                        <div class="list-unstyled list-hours mb-6 text-left mx-auto">
                            {% if user.is_staff %}
                                <p><a href="{% url 'event-create' %}">
                                    Create New Event
                                </a>
                                </p>
                            {% endif %}
                        </div>
                        {% if event_list %}
                            <div class="list-unstyled list-hours mb-6 text-left mx-auto">
                            {% for event in event_list %}
                                <p class="list-unstyled-item list-hours-item d-flex">
                                    <span class="text-start col-sm-4">
                                        <a class="text-left"
                                           href="{{ event.get_absolute_url }}">
                                            {{ event.title }}
                                        </a>
                                    </span>
                                    <span class="text-start col-sm-2 col-xs-2">({{ event.level }})</span>
                                    <span class="text-end col-sm-3 ">{{ event.date }} </span>
                                    <span class="text-end col-sm-3 ">
                                    {% if user.is_staff %}
                                        <a href="{% url 'event-update' event.id %}">
                                            Update</a>
                                        - <a href="{% url 'event-delete' event.id %}">
                                            Delete</a>
                                    {% endif %}
                                    </span>
                                </p>
                            {% endfor %}

                        {% else %}
                            <p>There are no on the calendar events at this time.</p>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

catalog/templates/footer.html
<footer class="footer text-faded text-center py-5">
    <div class="container"><p class="m-0 small">Copyright &copy; Coding Cohorts 2022</p>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>

catalog/templates/index.html
{% extends "base_generic.html" %}
{% block content %}
    <section class="page-section clearfix">
        <div class="container">
            <div class="intro">
                <img class="intro-img img-fluid mb-3 mb-lg-0 rounded"
                     src="/static/img/intro.jpg" alt="..."/>
                <div class="intro-text left-0 text-center bg-faded p-5 rounded">
                    <h2 class="section-heading mb-4">
                        <span class="section-heading-lower">Welcome to cohorts!</span>
                    </h2>
                    <p class="mb-3">Programming Cohorts are
                        open to anyone who wants to learn and
                        improve their web coding skills: HTML,
                        CSS, JavaScript, API, and database
                        skills by doing coding challenges in
                        a small group environment. The problems
                        will be targeted at beginner and intermediate l
                        evel programmers as well as talks.</p>
                    <div class="intro-button mx-auto">
                        <a class="btn btn-primary btn-xl"
                           href="{% url 'events' %}">See the Events
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}